name: Unit Testing

on:
  push:
    branches: ['main', 'dev', 'feature/workflow']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - name: Web point entry
      #   run: cd ./web/
      - name: Install modules
        run: |
          cd web/
          npm install
      - name: Run Jest
        run: |
          cd web/
          npm test 